import { Inter } from "next/font/google"
import "./globals.css"
import Header from "./components/Header/Header"
import SupabaseContext from "@/libs/supabase/supabase-context"
import ThemeProvider from "@/libs/contexts/ThemeContext"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<SupabaseContext>
					<Header />
					<main className=" mx-auto max-w-[1424px]">
						<ThemeProvider>{children}</ThemeProvider>
					</main>
				</SupabaseContext>
			</body>
		</html>
	)
}

// bg-slate-700 mx-[12rem]
