import { Inter } from "next/font/google"
import "./globals.css"
import React from "react"
import Header from "./components/Header/Header"
import AuthProvider from "@/libs/contexts/UserContext"

// import PrivateRoute from "@/libs/PrivateRoute"
// import { Profile } from "./components/Dashboard/dashboard"
// import Store from "./store/page"
// import NewPage from './newpage/page'

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<AuthProvider>
					<Header />
					{children}
				</AuthProvider>
			</body>
		</html>
	)
}
